# Generated by Django 5.1.2 on 2026-06-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=40)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('tel', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('end', models.CharField(blank=True, max_length=255)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('depto', models.CharField(max_length=120)),
                ('nome', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=120)),
                ('resp', models.CharField(blank=True, max_length=180)),
                ('tel', models.CharField(blank=True, max_length=40)),
                ('end', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['depto', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matricula', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=180)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('depto', models.CharField(max_length=120)),
                ('lotacao', models.CharField(max_length=200)),
                ('tel', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(max_length=120)),
                ('armeiro', models.CharField(max_length=120)),
                ('data_rec', models.DateField()),
                ('data_dev', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=60)),
                ('motivo', models.CharField(blank=True, max_length=180)),
                ('matricula', models.CharField(max_length=40)),
                ('policial', models.CharField(max_length=180)),
                ('depto', models.CharField(max_length=120)),
                ('lotacao', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=120)),
                ('serie', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('pecas', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-data_rec', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('patrimonio', models.CharField(blank=True, max_length=60)),
                ('descricao', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=80)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('serie', models.CharField(blank=True, max_length=120)),
                ('qtd_total', models.PositiveIntegerField(default=1)),
                ('qtd_disp', models.PositiveIntegerField(default=1)),
                ('qtd_min', models.PositiveIntegerField(default=1)),
                ('dt_aq', models.DateField(blank=True, null=True)),
                ('dt_val', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Disponivel', max_length=40)),
                ('obs', models.TextField(blank=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='core.fornecedor')),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Cautela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('data_saida', models.DateField()),
                ('data_prev', models.DateField(blank=True, null=True)),
                ('data_dev', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(max_length=40)),
                ('policial', models.CharField(max_length=180)),
                ('depto', models.CharField(max_length=120)),
                ('lotacao', models.CharField(max_length=200)),
                ('item_desc', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=80)),
                ('serie', models.CharField(blank=True, max_length=120)),
                ('qtd', models.PositiveIntegerField(default=1)),
                ('obs', models.TextField(blank=True)),
                ('status', models.CharField(default='Ativa', max_length=40)),
                ('condicao_dev', models.CharField(blank=True, max_length=80)),
                ('obs_dev', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cautelas', to='core.item')),
            ],
            options={
                'ordering': ['-data_saida', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('tipo', models.CharField(max_length=80)),
                ('item_desc', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=80)),
                ('qtd', models.PositiveIntegerField(default=1)),
                ('serie', models.CharField(blank=True, max_length=120)),
                ('policial', models.CharField(blank=True, max_length=180)),
                ('matricula', models.CharField(blank=True, max_length=40)),
                ('lotacao', models.CharField(blank=True, max_length=200)),
                ('num_cautela', models.CharField(blank=True, max_length=30)),
                ('obs', models.TextField(blank=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='core.item')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.CharField(max_length=120)),
                ('valor', models.CharField(max_length=120)),
                ('rotulo', models.CharField(max_length=180)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['grupo', 'ordem', 'rotulo'],
                'constraints': [models.UniqueConstraint(fields=('grupo', 'valor'), name='uq_opcaomenu_grupo_valor')],
            },
        ),
    ]
