# Generated by Django 5.1.2 on 2026-07-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sync_policial_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautela',
            name='depto',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='cautela',
            name='lotacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cautela',
            name='matricula',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='cautela',
            name='policial_nome',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='servico',
            name='depto',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='servico',
            name='lotacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servico',
            name='matricula',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='servico',
            name='policial_nome',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(max_length=80)),
                ('tipo', models.CharField(blank=True, max_length=120)),
                ('calibre', models.CharField(blank=True, max_length=60)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('nivel', models.CharField(blank=True, max_length=40)),
                ('tamanho', models.CharField(blank=True, max_length=40)),
                ('sexo', models.CharField(blank=True, max_length=40)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('serie', models.CharField(blank=True, max_length=120)),
                ('descricao', models.CharField(max_length=200)),
                ('qtd_total', models.PositiveIntegerField(default=1)),
                ('qtd_disp', models.PositiveIntegerField(default=1)),
                ('qtd_min', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='Pendente', max_length=40)),
                ('dt_aq', models.DateField(blank=True, null=True)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dt_val', models.DateField(blank=True, null=True)),
                ('obs', models.TextField(blank=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='core.fornecedor')),
            ],
            options={
                'ordering': ['-dt_aq', '-criado_em'],
            },
        ),
    ]
