# Generated by Django 5.1.2 on 2026-07-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cautela_depto_alter_cautela_lotacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='capacidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arma',
            name='comprimento_cano',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='arma',
            name='quantidade_carregadores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='capacidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='comprimento_cano',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='compra',
            name='quantidade_carregadores',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
