# Generated by Django 5.1.2 on 2026-07-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_compra_nf_empenho_tombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='policial',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
