# Generated by Django 5.1.2 on 2026-07-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_policial_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotacao',
            name='ais',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='lotacao',
            name='area_atuacao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
