export const CARGOS_POLICIAIS = [
  'Delegado de Policia',
  'Oficial Investigador',
  'Oficial Investigadora',
];

export const DEPARTAMENTOS_PADRAO = [
  'Assessoria Juridica',
  'Coordenadoria de Operacoes e Recursos Especiais',
  'Assessoria de Controle Interno',
  'Ouvidoria',
  'Assessoria de Comunicacao',
  'Assessoria ao Sistema de Justica',
  'Assessoria Superior de Policia Civil',
  'Coordenadoria de Plantoes',
  'Departamento de Inteligencia Policial',
  'Departamento Tecnico Operacional',
  'Departamento de Recuperacao de Ativos',
  'Departamento de Policia Especializada',
  'Departamento de Combate a Crimes Contra o Patrimonio',
  'Departamento de Repressao ao Crime Organizado',
  'Departamento de Protecao aos Grupos Vulneraveis',
  'Departamento de Homicidios e Protecao a Pessoa',
  'Departamento de Policia da Capital',
  'Departamento de Policia da Regiao Metropolitana',
  'Departamento de Policia do Interior Norte',
  'Departamento de Policia do Interior Sul',
  'Coordenadoria de Desenvolvimento Institucional e Planejamento',
  'Coordenadoria de Administracao e Financas',
  'Coordenadoria de Logistica',
  'Coordenadoria de Gestao de Pessoas',
  'Coordenadoria de Tecnologia da Informacao e Comunicacao',
  'Coordenadoria de Saude do Policial Civil',
  'Corregedoria-Geral de Policia Civil',
];
